// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGtvz0T7RcmuvG_X-5Rf95YZFsaAQHzCw',
    appId: '1:1868830897:web:1b64f1ae8c27a8c2e96a90',
    messagingSenderId: '1868830897',
    projectId: 'mdf-8e174',
    authDomain: 'mdf-8e174.firebaseapp.com',
    storageBucket: 'mdf-8e174.firebasestorage.app',
    measurementId: 'G-MT9GV1ZVMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNdMx3zCghmglWcwRlhz7Qw63JYbajNMQ',
    appId: '1:1868830897:android:464d88d32aed9935e96a90',
    messagingSenderId: '1868830897',
    projectId: 'mdf-8e174',
    storageBucket: 'mdf-8e174.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhNsqKkqU0E2JDNwksTNFyQNc3Njb0c5Y',
    appId: '1:1868830897:ios:9c3de21e4bd04259e96a90',
    messagingSenderId: '1868830897',
    projectId: 'mdf-8e174',
    storageBucket: 'mdf-8e174.firebasestorage.app',
    iosBundleId: 'com.example.mdfSat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhNsqKkqU0E2JDNwksTNFyQNc3Njb0c5Y',
    appId: '1:1868830897:ios:26e3178fc493ed0ae96a90',
    messagingSenderId: '1868830897',
    projectId: 'mdf-8e174',
    storageBucket: 'mdf-8e174.firebasestorage.app',
    iosBundleId: 'com.example.cryptoCoinsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGtvz0T7RcmuvG_X-5Rf95YZFsaAQHzCw',
    appId: '1:1868830897:web:6bd8c318b9e073c8e96a90',
    messagingSenderId: '1868830897',
    projectId: 'mdf-8e174',
    authDomain: 'mdf-8e174.firebaseapp.com',
    storageBucket: 'mdf-8e174.firebasestorage.app',
    measurementId: 'G-R75LQQC0Z0',
  );

}