# Поддерживаемая версия iOS
platform :ios, '13.0'

# Используем динамические фреймворки и modular headers для Firebase
use_frameworks!
use_modular_headers!

# Целевая сборка приложения
target 'Runner' do
  # Подключаем Flutter
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Поддержка тестов (если нужны)
  target 'RunnerTests' do
    inherit! :search_paths
    # Pods для тестов
  end
end

# Не трогай это, нужно для Flutter
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end